name: Checks with gradle

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Test with Gradle
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: current
        arguments: check 
